class MultipleCatchDemo
{
   public static void main(String[] args)
   {
	try
	{
	   int n1 = Integer.parseInt(args[0]);
	   int n2 = Integer.parseInt(args[1]);
	   int res = n1/n2;
	   System.out.println("Result = "+res);
	}
	catch(ArithmeticException e)
	{
	   System.out.println("Cannot divide by zero");
	}
	catch(ArrayIndexOutOfBoundsException e)
	{
	   System.out.println("Cannot access out of index");
	}
	catch(NumberFormatException e)
	{
	   System.out.println("Cannot convert String to number");
	}
	catch(RuntimeException e)
	{
	  System.out.println("Runtime Exception");
	}
	catch(Exception e)
	{
	   System.out.println("Exception Occured");
	}
   }
}